config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # staff specific pages
  get 'config', to: 'staff_portal#configuration'
  get 'staff-dashboard', to: 'staff_portal#dashboard', as: :staff_portal
  get 'residents', to: 'staff_portal#residents'

  get 'user-roles', to: 'staff_portal#user_roles', as: :user_roles
  get 'edit-role/:id', to: 'staff_portal#edit_role', as: :edit_role
  put 'edit-role', to: 'staff_portal#update_role'

  # resident specific pages
  get 'resident-dashboard', to: 'resident_portal#dashboard', as: :resident_portal
  get 'my-maintenance-requests', to: 'resident_portal#maintenance_requests', as: :resident_maintenance_requests

  # common pages
  get 'unauthorised', to: 'pages#unauthorised'

  # resources
  resources :rooms
  resources :lodgings
  resources :buildings
  resources :maintenance_requests

  devise_for :users

end

app/controllers/staff_portal_controller.rb
class StaffPortalController < ApplicationController
  before_action :authenticate_staff!

  def configuration
  end

  def dashboard
  end

  def residents
    @residents = User.where(role: "resident")
  end

  # view and change user roles
  def user_roles
    @users = User.all
  end

  def edit_role
    @user = User.find(params[:id])
    puts @user
  end

  def update_role
    @user = User.find(params[:id])
    if @user.update(user_role_param)
      redirect_to user_roles_path, notice: 'User role updated successfully.'
    else
      render :edit_role, notice: 'Unsuccessful'
    end
  end

  private
  def user_role_param
    params.require(:user).permit(:role)
  end
end

app/helpers/staff_portal_helper.rb
module StaffPortalHelper
end

app/views/staff_portal/configuration.html.erb
<h1>System Configuraion</h1>

<p>Add a new building</p>
<%= link_to "New Building", new_building_path %>

<p>Add a new lodging</p>
<%= link_to "New Lodging", new_lodging_path %>

<p>Add a new room</p>
<%= link_to "New Room", new_room_path %>

<p>Edit user permissions</p>
<%= link_to "Edit permissions", user_roles_path %>

app/views/staff_portal/dashboard.html.erb
<h1>StaffPortal#dashboard</h1>
<p>Find me in app/views/staff_portal/dashboard.html.erb</p>

app/views/staff_portal/edit_role.html.erb
<%= @user.email %>
<%= simple_form_for(@user, url: url_for(action: :update_role, controller: :staff_portal, id: @user.id), html: {method: :put}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :role %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/staff_portal/residents.html.erb
<table id="residents_table" class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Room Number</th>
      <th>Building</th>
    </tr>
  </thead>
  <tbody>
    <% @residents.each do |r| %>
      <tr>
        <td><%= r.first_name %></td>
        <td><%= r.last_name %></td>
        <td><%= r.room.lodging.code + "-" + r.room.number if r.room %></td>
        <td><%= r.room.lodging.building.name if r.room %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function () {
    $('#residents_table').DataTable();
  });
</script>

app/views/staff_portal/user_roles.html.erb
<p id="notice"><%= notice %></p>

<h1>User Roles</h1>

<table id="user_roles_table" class="table">
  <thead>
    <tr>
      <th width="30%">Name</th>
      <th width="30%">Email</th>
      <th width="20%">Current Role</th>
      <th width-"20%"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name + " " + user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Change Role', edit_role_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $(document).ready(function () {
    $('#user_roles_table').DataTable();
  });
</script>