config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # staff specific pages
  get 'config', to: 'staff_portal#configuration'
  get 'staff-dashboard', to: 'staff_portal#dashboard', as: :staff_portal
  get 'residents', to: 'staff_portal#residents'

  get 'user-roles', to: 'staff_portal#user_roles', as: :user_roles
  get 'edit-role/:id', to: 'staff_portal#edit_role', as: :edit_role
  put 'edit-role', to: 'staff_portal#update_role'

  # resident specific pages
  get 'resident-dashboard', to: 'resident_portal#dashboard', as: :resident_portal
  get 'my-maintenance-requests', to: 'resident_portal#maintenance_requests', as: :resident_maintenance_requests

  # common pages
  get 'unauthorised', to: 'pages#unauthorised'

  # resources
  resources :rooms
  resources :lodgings
  resources :buildings
  resources :maintenance_requests

  devise_for :users

end

app/models/building.rb
class Building < ApplicationRecord
  has_many :lodgings, :dependent => :destroy

  def current_capacity
    cap = 0
    lodgings.each { |l| cap+=l.current_capacity }
    return cap
  end

  def total_capacity
    cap = 0
    lodgings.each { |l| cap+=l.total_capacity }
    return cap
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name, :street, :city, :postcode, :state, :country)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= simple_form_for(@building) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :postcode %>
    <%= f.input :state %>
    <%= f.input :country %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table id="buildings_table" class="table">
  <thead>
    <tr>
      <th width="20%">Name</th>
      <th width="50%">Address</th>
      <th width="15%">Capacity</th>
      <th width-"5%">Views</th>
      <th width-"5%"></th>
      <th width-"5%"></th>
    </tr>
  </thead>
  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.name %></td>
        <td><%= building.street + ", " + building.city + ", " + building.postcode + ", " + building.state + ", " + building.country %></td>
        <td><%= building.current_capacity %>/<%= building.total_capacity %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

<script type="text/javascript">
  $(document).ready(function () {
    $('#buildings_table').DataTable();
  });
</script>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @building.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @building.city %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @building.postcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @building.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @building.country %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>