config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # staff specific pages
  get 'config', to: 'staff_portal#configuration'
  get 'staff-dashboard', to: 'staff_portal#dashboard', as: :staff_portal
  get 'residents', to: 'staff_portal#residents'

  get 'user-roles', to: 'staff_portal#user_roles', as: :user_roles
  get 'edit-role/:id', to: 'staff_portal#edit_role', as: :edit_role
  put 'edit-role', to: 'staff_portal#update_role'

  # resident specific pages
  get 'resident-dashboard', to: 'resident_portal#dashboard', as: :resident_portal
  get 'my-maintenance-requests', to: 'resident_portal#maintenance_requests', as: :resident_maintenance_requests

  # common pages
  get 'unauthorised', to: 'pages#unauthorised'

  # resources
  resources :rooms
  resources :lodgings
  resources :buildings
  resources :maintenance_requests

  devise_for :users

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :lodging, :dependent => :destroy
  belongs_to :user, optional: true, :dependent => :destroy

  def current_capacity
    return 1 if user
    return 0
  end

  def total_capacity
    1
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:lodging_id, :user_id, :number)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :lodging %>
    <%= f.association :user, :include_blank => false, :label_method => lambda { |user| "#{user.room.present?} #{user.first_name} #{user.last_name}" } %>
    <%= f.input :number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Lodging</th>
      <th>User</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.lodging %></td>
        <td><%= room.user %></td>
        <td><%= room.number %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lodging:</strong>
  <%= @room.lodging %>
</p>

<p>
  <strong>User:</strong>
  <%= @room.user %>
</p>

<p>
  <strong>Number:</strong>
  <%= @room.number %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>