config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # staff specific pages
  get 'config', to: 'staff_portal#configuration'
  get 'staff-dashboard', to: 'staff_portal#dashboard', as: :staff_portal
  get 'residents', to: 'staff_portal#residents'

  get 'user-roles', to: 'staff_portal#user_roles', as: :user_roles
  get 'edit-role/:id', to: 'staff_portal#edit_role', as: :edit_role
  put 'edit-role', to: 'staff_portal#update_role'

  # resident specific pages
  get 'resident-dashboard', to: 'resident_portal#dashboard', as: :resident_portal
  get 'my-maintenance-requests', to: 'resident_portal#maintenance_requests', as: :resident_maintenance_requests

  # common pages
  get 'unauthorised', to: 'pages#unauthorised'

  # resources
  resources :rooms
  resources :lodgings
  resources :buildings
  resources :maintenance_requests

  devise_for :users

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SAM</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
      </ul>
      <!--
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
      -->
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <% if user_signed_in? %>
      <center>
        <img src="<%= current_user.image_url ? current_user.image_url : image_path('unknownuser.png') %>" class="img-circle img-responsive">
        <h4><%= current_user.first_name + " " + current_user.last_name %></h4>
      </center>
      <br>
      <% if current_user.role == 'resident' %>
        <li class="<%= 'active' if is_active_link?(resident_portal_path, :exclusive)%>">
          <%= active_link_to 'Resident Dashboard', resident_portal_path %>
        </li>
        <li class="<%= 'active' if is_active_link?(show_user_path, :exclusive)%>">
          <%= active_link_to 'Profile', show_user_path %>
        </li>
        <li class="<%= 'active' if is_active_link?("#", :exclusive)%>">
          <%= active_link_to 'Pay Rent', '#' %>
        </li>
        <li class="<%= 'active' if is_active_link?(resident_maintenance_requests_path, :exclusive)%>">
          <%= active_link_to 'Maintenance Requests', resident_maintenance_requests_path %>
        </li>
      <% elsif current_user.role == 'staff' %>
        <li class="<%= 'active' if is_active_link?(staff_portal_path, :exclusive)%>">
          <%= active_link_to 'Dashboard', staff_portal_path %>
        </li>
        <li class="<%= 'active' if is_active_link?(show_user_path, :exclusive)%>">
          <%= active_link_to 'Profile', show_user_path %>
        </li>
        <li class="<%= 'active' if is_active_link?(residents_path, :exclusive)%>">
          <%= active_link_to 'Residents', residents_path %>
        </li>
        <li class="<%= 'active' if is_active_link?(buildings_path, :exclusive)%>">
          <%= active_link_to 'Buildings', buildings_path %>
        </li>
        <li class="<%= 'active' if is_active_link?(maintenance_requests_path, :exclusive)%>">
          <%= active_link_to 'Maintenance Requests', maintenance_requests_path %>
        </li>
        <li class="<%= 'active' if is_active_link?(config_path, :exclusive)%>">
          <%= active_link_to 'Config', config_path %>
        </li>
      <% end %>
      <li><%= active_link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samrails</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container-fluid">
      <div class="row">
        <% if user_signed_in? %>
          <%= render 'layouts/sidebar' %>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <%= yield %>
          </div>
        <% else %>
          <%= yield %>
        <% end %>
      </div>
    </div>

  </body>
</html>